<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><RuntimeIdentifier>win-x64</RuntimeIdentifier>
<SelfContained>true</SelfContained><PublishSingleFile>true</PublishSingleFile><EnableCompressionInSingleFile>true</EnableCompressionInSingleFile><IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
<ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>GotlandRing-Portable</AssemblyName><DebugType>none</DebugType><DebugSymbols>false</DebugSymbols>
<ApplicationIcon>Impreza.ico</ApplicationIcon>
<Version>0.3.0-awd.5</Version>
<Company>Mannetroll Solutions AB</Company><Product>Gotland Ring - Impreza</Product>
</PropertyGroup>
<ItemGroup><EmbeddedResource Include="Game.zip" LogicalName="Game.zip" /></ItemGroup>
</Project>
